### ISSUE TITLE
V1.2 assets dont have latest changes

### ISSUE THREAD

**Issue by datajoy-eric** [anuraag016/Jest-Coverage-Diff#21]
Hi there,

Recently i opened and closed https://github.com/anuraag016/Jest-Coverage-Diff/issues/19 a bit too quickly. After testing on our repo, I have realized that the assets found here: https://github.com/anuraag016/Jest-Coverage-Diff/releases/tag/V1.2
use the same code in the `dist` folder as in master (https://github.com/anuraag016/Jest-Coverage-Diff/blob/master/dist/index.js#L2027) which does not include the latest changes to support `afterSwitchCommand`

I suspect the `dist` folder needs to be updated and then another version published?

My reproduction steps are:
1. Create a PR that deletes a package from `package.json`
2. Push
3. observe that `afterSwitchCommand` is not being called

Thanks again for your support!

**Comment by anuraag016** [comment]
Hey Thanks again, I have created a new release after building the code, Please use V1.3,
I have also opened an issue https://github.com/anuraag016/Jest-Coverage-Diff/issues/23 to create a new workflow that would build the code automatically and push to master or at least open a pr before a release is made, so that similar mistake is not made in the future 😅 
Thanks Again for bringing the issue up 😄

**Comment by datajoy-eric** [comment]
Thanks for the fix :) Just tested our pipeline and works as excepted!
