### ISSUE TITLE
feat: Use Same Comment for Updates

### ISSUE THREAD

**Issue by therynamo** [anuraag016/Jest-Coverage-Diff#27]
Hey there! Thanks for building out this coverage diff action! 

I was using [jest-coverage-reporting-action](https://github.com/ArtiomTr/jest-coverage-report-action) previously and it was taking an exceptionally long time to run. I gave your action a shot and it was far faster, so 👏 . One thing that was nice though - was their ability to comment back to the same issue. I think that would be a valuable add here so that PRs aren't receiving a new comment with every commit. 

Let me know what you think - I'd be happy to try and take a stab at it too if you don't have the bandwidth.

**Comment by anuraag016** [comment]
Hey @therynamo! Thanks a lot for opening this issue, you have a valid point here, its worth having this feature as an option so that it can be used as required. I remember using one single comment thing for one of my test action, I might still have that code somewhere. Let me see if I can salvage the same code and use it here.

**Comment by therynamo** [comment]
Awesome @anuraag016 - excited to see this - let me know if I can help in any way. 👍
